version: '3.7'

services:
  application:
    container_name: shopping-cart-application
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - shopping-cart-network
    depends_on:
      - postgres
  postgres:
    container_name: shopping-cart-postgres
    image: postgres:12
    networks:
      - shopping-cart-network
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: shopping-cart
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  shopping-cart-network:
volumes:
  pgdata: